# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20200210_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/insta2.jpeg', upload_to=''),
        ),
    ]
